### ISSUE TITLE
Repo rename from  moodle-quizzaccess_sebserver to moodle-quizaccess_sebserver

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/moodle-quizaccess_sebserver#1]
Dear @nexterday maybe for consistency and in order not to confuse people you should align the repository name with the Moodle plugin name, hence "moodle-quizaccess_sebserver".

**Comment by nexterday** [comment]
Cheers Luca, didn't notice the extra z.

**Comment by lucaboesch** [comment]
Thanks Amr!
Please notify Andreas Hefti, he has a link in the SEB Server README.md.
